### ISSUE TITLE
Seasonal affective disorder therapy. SAD lamps.

### ISSUE THREAD

**Issue by diimdeep** [Jimnotgym/Hacking_Depression#3]
[Seasonal affective disorder (SAD)](https://en.wikipedia.org/wiki/Seasonal_affective_disorder)

I am using DIY light source every morning for 30 min while doing guided meditation (headspace)

You need >10000 Lux light source.

https://news.ycombinator.com/item?id=10590068 . 
https://motherboard.vice.com/en_us/article/z43ex9/depression-fighting-sad-lamps-arent-just-for-your-winter-blues

https://news.ycombinator.com/item?id=16146932 . 
http://justinmklam.com/posts/2018/01/sad-lamp/ . 

http://lukeskaff.com/diy-sunlight-simulator-light-therapy-full-spectrum/ . 
https://meaningness.com/metablog/sad-light-lumens/talk . 
https://meaningness.com/metablog/sad-light-led-lux .

**Comment by Jimnotgym** [comment]
Now that is interesting. The propriety SAD lamps tend to suck or be very expensive. Do you think it would be best to dedicate a newsection on "Light therapy" for your links?

**Comment by Schachte** [comment]
Ironically the founder of ycombinator which owns hacker news wrote a blog recently mentioning his daily usage of a lamp like this.

Seems interesting.

**Comment by Jimnotgym** [comment]
I'll draft a section for it

**Comment by Jimnotgym** [comment]
It is really great to have our first contributions today. Thank you both for our help.
